apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: production
  labels:
    app: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      serviceAccountName: cicd-sa
      containers:
        - name: django-container
          image: findcoding/django-iiitdrive:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "iiitdrive.settings"
              
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: production
  labels:
    app: django-app
spec:
  type: ClusterIP
  selector:
    app: django-app
  ports:
    - name: http
      port: 80        
      targetPort: 8000
