apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-container
          image: findcoding/django-iiitdrive:latest   # <--- your Django image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000   # typical for Django runserver / gunicorn
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "iiitdrive.settings"
            # Example: pull secret key from Kubernetes Secret (optional)
            # - name: DJANGO_SECRET_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: django-secret
            #       key: secret_key
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: django-app
spec:
  type: ClusterIP
  selector:
    app: django-app
  ports:
    - name: http
      port: 80        # service port inside cluster
      targetPort: 8000 # containerPort in the pod
