# Generated by Django 4.1.3 on 2022-12-11 14:01

from django.db import migrations, models
import iiitdrive.models
import iiitdrive.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(help_text='only IIITD emails', max_length=50, unique=True, validators=[iiitdrive.models.AllowlistEmailValidator(allowlist=['iiitd.ac.in'])], verbose_name='Email address')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email Verified?')),
                ('email_verification_token', models.CharField(default=iiitdrive.utils.get_email_verification_token, max_length=32, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active?')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is Admin?')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
