# Generated by Django 4.1.3 on 2022-12-10 19:58

from django.db import migrations, models
import iiitdrive.utils


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdrive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verification_token',
            field=models.CharField(default=iiitdrive.utils.get_email_verification_token, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
