# Generated by Django 4.1.3 on 2022-12-11 21:09

from django.db import migrations
import iiitdrive.models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdrive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=iiitdrive.models.LowercaseEmailField(help_text='only IIITD emails', max_length=50, unique=True, validators=[iiitdrive.models.AllowlistEmailValidator(allowlist=['iiitd.ac.in'])], verbose_name='Email address'),
        ),
    ]
