# Generated by Django 4.1.3 on 2022-12-10 21:16

from django.db import migrations, models
import iiitdrive.models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdrive', '0002_alter_customuser_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True, validators=[iiitdrive.models.AllowlistEmailValidator(allowlist=['iiitd.ac.in'])], verbose_name='Email address'),
        ),
    ]
