# Generated by Django 4.1.3 on 2022-12-11 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iiitdrive.models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdrive', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', iiitdrive.models.LowercaseCharField(max_length=25, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to=iiitdrive.models.change_filename)),
                ('about_me', models.CharField(blank=True, default='', max_length=200)),
                ('hobbies', models.ManyToManyField(related_name='users', to='iiitdrive.hobby')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
