# Generated by Django 4.1.3 on 2022-12-12 09:51

from django.db import migrations
import iiitdrive.model_fields
import iiitdrive.models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdrive', '0003_hobby_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profile_picture',
            field=iiitdrive.model_fields.RestrictedFileField(blank=True, null=True, upload_to=iiitdrive.models.change_filename),
        ),
    ]
