# Generated by Django 4.1.3 on 2022-12-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdrive', '0004_alter_userdetails_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='hobbies',
        ),
        migrations.DeleteModel(
            name='Hobby',
        ),
    ]
