# Generated by Django 4.1.3 on 2022-12-13 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdrive', '0005_remove_userdetails_hobbies_delete_hobby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('link', models.URLField()),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='iiitdrive.userdetails')),
            ],
            options={
                'unique_together': {('user_details', 'name')},
            },
        ),
    ]
