# Generated by Django 4.1.3 on 2022-12-13 11:19

from django.db import migrations, models
import iiitdrive.model_fields
import iiitdrive.models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdrive', '0006_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResouceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=iiitdrive.models.change_filename_with_user)),
            ],
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profile_picture',
            field=iiitdrive.model_fields.RestrictedFileField(blank=True, null=True, upload_to=iiitdrive.models.change_filename_with_user),
        ),
    ]
