# Generated by Django 4.1.3 on 2022-12-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiitdrive', '0008_resourcefile_userfiles_delete_resoucefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcefile',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcefile',
            name='type',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
